services:
  mysql:
    image: 'mysql:latest'
    restart: always
    environment:
      - 'MYSQL_DATABASE=posts_tdd_1'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3336:3306'

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      - 'PMA_ARBITRARY=1'
    ports:
      - '3337:80'	